In [1]:
print("jai ho ganesha")

jai ho ganesha


In [2]:
pip install torch


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import torch
print(torch.__version__)



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\Program Files\Python312\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "d:\Program Files\Python312\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "d:\Program Files\Python312\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "d:\Program Files\Python312\Lib\s

2.4.0+cpu


In [5]:
tensor1=torch.ones(3,4)
print(type(tensor1))
print(tensor1)

<class 'torch.Tensor'>
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
torch.manual_seed(100)
random=torch.rand(2,3)
random

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
x=torch.empty(4,2,3)
x

tensor([[[-6.2946e-05,  1.8847e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [8]:
some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

tensor([ 2,  3,  5,  7, 11, 13, 17, 19])


# The simplest way to set the underlying data type of a tensor is with an optional argument at creation time. In the first line of the cell above, we set dtype=torch.int16 for the tensor a. When we print a, we can see that it’s full of 1 rather than 1. - Python’s subtle cue that this is an integer type rather than floating point.

# The other way to set the datatype is with the .to() method. In the cell above, we create a random floating point tensor b in the usual way. Following that, we create c by converting b to a 32-bit integer with the .to() method. Note that c contains all the same values as b, but truncated to integers


In [9]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64)
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


# Tensor Broadcasting
# Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. In the example above, the one-row, four-column tensor is multiplied by both rows of the two-row, four-column tensor.

In [20]:
random=torch.rand(2,4)
double= random * (torch.ones(1,4)+2)
print(random)
print(double)

tensor([[0.5557, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003]])
tensor([[1.6672, 2.9311, 1.3321, 2.8435],
        [2.2335, 1.4676, 0.7277, 2.1010]])


In [23]:
a = torch.ones(4, 3, 2)
b = a * torch.rand( 3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.5277, 0.2472],
         [0.7909, 0.4235],
         [0.0169, 0.2209]],

        [[0.5277, 0.2472],
         [0.7909, 0.4235],
         [0.0169, 0.2209]],

        [[0.5277, 0.2472],
         [0.7909, 0.4235],
         [0.0169, 0.2209]],

        [[0.5277, 0.2472],
         [0.7909, 0.4235],
         [0.0169, 0.2209]]])


In [25]:
import math
# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [30]:
torch.manual_seed(100)
a = torch.ones(2, 2)
b = torch.rand(2, 2)
print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)


Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

After adding:
tensor([[1.1117, 1.8158],
        [1.2626, 1.4839]])
tensor([[1.1117, 1.8158],
        [1.2626, 1.4839]])
tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

After multiplying
tensor([[0.0125, 0.6656],
        [0.0689, 0.2341]])
tensor([[0.0125, 0.6656],
        [0.0689, 0.2341]])
